### PR TITLE
Fixed EKF origin error

### PR DESCRIPTION
**Pull request by evan-palmer**
# Checklist

- [x] I have performed a thorough review of my code
- [x] I have sufficiently commented my code
- [x] The implementation follows the project style conventions
- [x] All project unit tests are passing
- [x] If relevant, documentation has been provided or updated to discuss the changes made
- [x] System integration tests were performed successfully

## Changes Made

This PR resolves an issue in which the EKF origin is not set. This is required to perform localization using one of the provided localizers on a vehicle.

## Associated Issues

go crazy

## Testing

Testing was performed in simulation. Ironically, this may actually solve the real problem discussed in #64

### CODE REVIEW

**Comment by evan-palmer** [comment]
> This pull request is in conflict. Could you fix it @evan-palmer?

OOOHHHH NOW YOU WORK SMH

**Comment by evan-palmer** [comment]
@ssicari This PR is technically targeting a different issue that I am experiencing on hardware, but I observed that it allows for triggering guided mode and setting target positions (though I didn't test out mission planning). You may want to try this version out to see if it resolves your issues

**Comment by ssicari** [comment]
> @ssicari This PR is technically targeting a different issue that I am experiencing on hardware, but I observed that it allows for triggering guided mode and setting target positions (though I didn't test out mission planning). You may want to try this version out to see if it resolves your issues

I pulled and updated main branch, rebuilt with colcon build and resourced the environment. Same error saying GUIDED MODE requires GPS position. However, I see two warnings that might be causing the problem. One warning is in the qgroundcontrol terminal that says, "Gelocation disabled for UID 1001, GDBus.error.org Access Denied". The other warning I think is the main problem, and I don't recall seeing to before. It is in the terminal that starts the sim and says, "mavros.global_position GP: No GPS fix." I am going to focus on that to see if I can figure out what is causing that and if it will fix it. Thank you!

**Comment by ssicari** [comment]
> > @ssicari This PR is technically targeting a different issue that I am experiencing on hardware, but I observed that it allows for triggering guided mode and setting target positions (though I didn't test out mission planning). You may want to try this version out to see if it resolves your issues
> 
> I pulled the updated main branch, rebuilt with colcon build and resourced the environment. Same error saying GUIDED MODE requires GPS position. However, I see two warnings that might be causing the problem. One warning is in the qgroundcontrol terminal that says, "Gelocation disabled for UID 1001, GDBus.error.org Access Denied". The other warning I think is the main problem, and I don't recall seeing to before. It is in the terminal that starts the sim and says, "mavros.global_position GP: No GPS fix." I am going to focus on that to see if I can figure out what is causing that and if it will fix it. Thank you!

Also looking at the commit history I see that in the mavros.yaml file there is a line that was added that is not in the repo either online or when I pulled it. I will attach screen shots to show the discrepancy. 

image
Screenshot from 2023-08-16 13-44-29

The line "component_id: 190" is gone. Maybe I am missing another part of the commit history where it was deleted? But I do not see it in main or hinsdale-staging-1 either on my computer after pulling the updated branched or on the github website.

**Comment by ssicari** [comment]
> > @ssicari This PR is technically targeting a different issue that I am experiencing on hardware, but I observed that it allows for triggering guided mode and setting target positions (though I didn't test out mission planning). You may want to try this version out to see if it resolves your issues
> 
> I pulled the updated main branch, rebuilt with colcon build and resourced the environment. Same error saying GUIDED MODE requires GPS position. However, I see two warnings that might be causing the problem. One warning is in the qgroundcontrol terminal that says, "Gelocation disabled for UID 1001, GDBus.error.org Access Denied". The other warning I think is the main problem, and I don't recall seeing to before. It is in the terminal that starts the sim and says, "mavros.global_position GP: No GPS fix." I am going to focus on that to see if I can figure out what is causing that and if it will fix it. Thank you!

It seems some of the changes are only on the bluerov2_heavy_reach. When I try to run 
```ros2 run blue_bringup bluerov2_heavy_reach.launch.py use_sim:=true```
it does not work and gets 
```No JSON sensor message received, resending servos```
I am wondering if maybe that's why the changes still don't work. I am going to look into the --show-args to see if there are other parameters I need to change to get the heavy_reach versoin to run. Also what is the difference between heavy and heavy_reach. I initially thought that the reach version might have a gripper but after downloading the .dae file I didn't seem to really notice a difference in the model, maybe I missed something. Thank you!

**Comment by evan-palmer** [comment]
> I pulled the updated main branch, rebuilt with colcon build and resourced the environment. Same error saying GUIDED MODE requires GPS position. However, I see two warnings that might be causing the problem. One warning is in the qgroundcontrol terminal that says, "Gelocation disabled for UID 1001, GDBus.error.org Access Denied". The other warning I think is the main problem, and I don't recall seeing to before. It is in the terminal that starts the sim and says, "mavros.global_position GP: No GPS fix." I am going to focus on that to see if I can figure out what is causing that and if it will fix it. Thank you!

The `Gelocation disabled for UID 1001, GDBus.error.org Access Denied` is interesting. I haven't seen that one before. This error `mavros.global_position GP: No GPS fix` shouldn't cause any problems(?). That pops up when QGC is open with the `global_position` MAVROS pluging launched. The `global_position` plugin is necessary to set the EKF origin.

> It seems some of the changes are only on the bluerov2_heavy_reach. 

Yeah I forgot to update the `manager.yaml` file in the latest PR. There are too many models for me to keep track of :smiley: Should be updated to support the other versions now.

> Also what is the difference between heavy and heavy_reach. I initially thought that the reach version might have a gripper but after downloading the .dae file I didn't seem to really notice a difference in the model, maybe I missed something. Thank you!

The BlueROV2 Heavy Reach model moves the thrusters from the upper chassis to the lower chassis to support the integration of manipulators. I have a separate project that is currently private which includes support for manipulation with the Reach Alpha 5 manipulator, but I am currently working on getting the core features cleaned up and ready prior to making it public.

**Comment by ssicari** [comment]
> > I pulled the updated main branch, rebuilt with colcon build and resourced the environment. Same error saying GUIDED MODE requires GPS position. However, I see two warnings that might be causing the problem. One warning is in the qgroundcontrol terminal that says, "Gelocation disabled for UID 1001, GDBus.error.org Access Denied". The other warning I think is the main problem, and I don't recall seeing to before. It is in the terminal that starts the sim and says, "mavros.global_position GP: No GPS fix." I am going to focus on that to see if I can figure out what is causing that and if it will fix it. Thank you!
> 
> The `Gelocation disabled for UID 1001, GDBus.error.org Access Denied` is interesting. I haven't seen that one before. This error `mavros.global_position GP: No GPS fix` shouldn't cause any problems(?). That pops up when QGC is open with the `global_position` MAVROS pluging launched. The `global_position` plugin is necessary to set the EKF origin.
> 
> > It seems some of the changes are only on the bluerov2_heavy_reach.
> 
> Yeah I forgot to update the `manager.yaml` file in the latest PR. There are too many models for me to keep track of 😃 Should be updated to support the other versions now.
> 
> > Also what is the difference between heavy and heavy_reach. I initially thought that the reach version might have a gripper but after downloading the .dae file I didn't seem to really notice a difference in the model, maybe I missed something. Thank you!
> 
> The BlueROV2 Heavy Reach model moves the thrusters from the upper chassis to the lower chassis to support the integration of manipulators. I have a separate project that is currently private which includes support for manipulation with the Reach Alpha 5 manipulator, but I am currently working on getting the core features cleaned up and ready prior to making it public.

Ah I see. I was struggling to find information on the mavros.global_position and kind of just assumed it could be the cause of the problem with guided mode still saying it needs a position. I will say sometimes the NO GPS fix does pop up even if I don't open Qgroundcontrol and try to just use the ROS CLI to change to guided mode. I can look more into the Geolocation error more as well. I tested the models with the changes, still can't seem to get them into guided mode and still can't get the heavy reach model to run.(However that's not a priority right now.) I will still keep going at this from my end. Thanks for the response!

**Comment by ssicari** [comment]
> @ssicari This PR is technically targeting a different issue that I am experiencing on hardware, but I observed that it allows for triggering guided mode and setting target positions (though I didn't test out mission planning). You may want to try this version out to see if it resolves your issues
y
Hey,
I am still struggling to get this to work with guided mode. I am thinking of wiping my machine and reinstalling everything again to see if there is something hidden away that is interfering with this. Do you have any other ideas I could also try as well to try to get this up and running. I am getting the same errors and warnings as before. I have also went back and tried to play around with the EK3 parameters to see if that would fix anything, but I still couldn't get it working.
Thank you!

**Pull request merged**
